libslic3r: Fix missing DBL_MAX constant
/run/ccache/bin/c++ -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_NO_LIB -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_NO_LIB -DBOOST_IOSTREAMS_NO_LIB -DBOOST_LOCALE_NO_LIB -DBOOST_LOG_NO_LIB -DBOOST_REGEX_NO_LIB -DBOOST_SYSTEM_NO_LIB -DBOOST_THREAD_NO_LIB -DHAVE_FREETYPE -DHAVE_OPENGL_EXT -DHAVE_XLIB -DLIBNEST2D_GEOMETRIES_libslic3r -DLIBNEST2D_OPTIMIZER_nlopt -DLIBNEST2D_STATIC -DLIBNEST2D_THREADING_tbb -DOCC_CONVERT_SIGNALS -DOPENVDB_OPENEXR_STATICLIB -DOPENVDB_STATICLIB -DSLIC3R_GUI -DTBB_USE_CAPTURED_EXCEPTION=0 -DUNICODE -DUSE_TBB -DWXINTL_NO_GETTEXT_MACRO -D_UNICODE -DwxNO_UNSAFE_WXSTRING_CONV -DwxUSE_UNICODE -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/run/build/BambuStudio/src -I/run/build/BambuStudio/build/src/platform -I/run/build/BambuStudio/src/libslic3r -I/run/build/BambuStudio/build/src/libslic3r -I/run/build/BambuStudio/deps/build/destdir/usr/local/include/opencascade -I/run/build/BambuStudio/src/libnest2d/include -I/run/build/BambuStudio/src/miniz -I/run/build/BambuStudio/src/glu-libtess/include -I/run/build/BambuStudio/src/clipper2/Clipper2Lib/include -isystem /run/build/BambuStudio/src/eigen -isystem /run/build/BambuStudio/src/libigl -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include -isystem /run/build/BambuStudio/deps/build/destdir/usr/local/include/OpenEXR -std=gnu++20 -fext-numeric-literals -Wall -Wno-reorder -O3 -DNDEBUG -std=gnu++17 -fPIC -fsigned-char -Werror=return-type -Wno-ignored-attributes -Wno-unknown-pragmas -DOPENVDB_ABI_VERSION_NUMBER=8 -MD -MT src/libslic3r/CMakeFiles/libslic3r.dir/GCode/CoolingBuffer.cpp.o -MF src/libslic3r/CMakeFiles/libslic3r.dir/GCode/CoolingBuffer.cpp.o.d -o src/libslic3r/CMakeFiles/libslic3r.dir/GCode/CoolingBuffer.cpp.o -c /run/build/BambuStudio/src/libslic3r/GCode/CoolingBuffer.cpp
In file included from /run/build/BambuStudio/src/libslic3r/GCode/CoolingBuffer.cpp:1:
/run/build/BambuStudio/src/libslic3r/GCode/../GCode.hpp:413:99: error: ‘DBL_MAX’ was not declared in this scope
  413 |     std::string travel_to(const Point &point, ExtrusionRole role, std::string comment, double z = DBL_MAX);
      |                                                                                                   ^~~~~~~
/run/build/BambuStudio/src/libslic3r/GCode/../GCode.hpp:22:1: note: ‘DBL_MAX’ is defined in header ‘<cfloat>’; did you forget to ‘#include <cfloat>’?
   21 | #include "libslic3r/ObjectID.hpp"
  +++ |+#include <cfloat>
   22 |