FIX: Fix missing boost:: declarations
/run/build/BambuStudio/src/slic3r/GUI/DeviceCore/DevConfigUtil.cpp: In static member function ‘static std::map<std::__cxx11::basic_string<char>, std::vector<std::__cxx11::basic_string<char> > > Slic3r::DevPrinterConfigUtil::get_all_subseries(std::string)’:
/run/build/BambuStudio/src/slic3r/GUI/DeviceCore/DevConfigUtil.cpp:167:21: error: ‘boost::filesystem’ has not been declared
  167 |         if (!boost::filesystem::exists(from_dir))
      |                     ^~~~~~~~~~

/run/build/BambuStudio/src/slic3r/Utils/HelioDragon.cpp: In member function ‘void Slic3r::HelioBackgroundProcess::clear_helio_file_cache()’:
/run/build/BambuStudio/src/slic3r/Utils/HelioDragon.cpp:1200: error: ‘remove’ is not a member of ‘boost::nowide’
 1200 |             int deleted = boost::nowide::remove(original_path_name.c_str());