FIX: Fix missing boost::prior declaration
In file included from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Intersections_3/Plane_3_Triangle_3.h:25,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/intersection_3.h:59,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Kernel/function_objects.h:29,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Cartesian/function_objects.h:20,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Cartesian/Cartesian_base.h:62,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Simple_cartesian.h:20,
                 from /run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /run/build/BambuStudio/src/libslic3r/Geometry/VoronoiUtilsCgal.cpp:1:
/run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Intersections_3/internal/Plane_3_Triangle_3_intersection.h: In function ‘typename CGAL::Intersection_traits<K, typename K::Plane_3, typename K::Triangle_3>::result_type CGAL::Intersections::internal::intersection(const typename K::Plane_3&, const typename K::Triangle_3&, const K&)’:
/run/build/BambuStudio/deps/build/destdir/usr/local/include/CGAL/Intersections_3/internal/Plane_3_Triangle_3_intersection.h:144:65: error: ‘prior’ is not a member of ‘boost’; did you mean ‘boost::mpl::prior’?
  144 |            k.construct_segment_3_object()(*pts.begin(), *boost::prior(pts.end())));
      |                                                                 ^~~~~