FIX: Fix missing std::stack declaration
/run/build/BambuStudio/src/libslic3r/Fill/FillRectilinear.cpp: In function ‘void Slic3r::adjust_sort_for_segment_intersections(std::vector<SegmentIntersection>&)’:
/run/build/BambuStudio/src/libslic3r/Fill/FillRectilinear.cpp:371:10: error: ‘stack’ is not a member of ‘std’
  371 |     std::stack<IntersectionType> stack;
      |          ^~~~~
/run/build/BambuStudio/src/libslic3r/Fill/FillRectilinear.cpp:36:1: note: ‘std::stack’ is defined in header ‘<stack>’; this is probably fixable by adding ‘#include <stack>’
   35 | #include <cassert>
  +++ |+#include <stack>
   36 |