FIX: Fix missing tbb declaration
/run/build/BambuStudio/src/libslic3r/Interlocking/InterlockingGenerator.cpp: In static member function ‘static void Slic3r::InterlockingGenerator::generate_embedding_wall(Slic3r::PrintObject*)’:
/run/build/BambuStudio/src/libslic3r/Interlocking/InterlockingGenerator.cpp:40:5: error: ‘tbb’ has not been declared
   40 |     tbb::parallel_for(
      |     ^~~