FIX: Fix missing polygon primitives declaration
/run/build/BambuStudio/src/libslic3r/GCode/WipeTower.hpp:31:12: error: ‘TriangleMesh’ does not name a type
   31 |     static TriangleMesh                 its_make_rib_tower(float width, float depth, float height, float rib_length, float rib_width, bool fillet_wall);
      |            ^~~~~~~~~~~~
<snip>
/run/build/BambuStudio/src/libslic3r/GCode/WipeTower.hpp:33:12: error: ‘Polygon’ does not name a type
   33 |     static Polygon                      rib_section(float width, float depth, float rib_length, float rib_width, bool fillet_wall);
      |            ^~~~~~~
<snip>
/run/build/BambuStudio/src/libslic3r/GCode/WipeTower.hpp:200:21: error: ‘Polylines’ was not declared in this scope
  200 |     std::map<float, Polylines> get_outer_wall() const
      |                     ^~~~~~~~~
<snip>