FIX: Fix missing ExPolygons type declaration
In file included from /run/build/BambuStudio/src/libslic3r/Clipper2Utils.cpp:1:
/run/build/BambuStudio/src/libslic3r/Clipper2Utils.hpp:11:1: error: ‘ExPolygons’ does not name a type; did you mean ‘Polygons’?
   11 | ExPolygons         union_ex_2(const Polygons &expolygons);
      | ^~~~~~~~~~
      | Polygons