FIX: Fix missing std::map declaration
/run/build/BambuStudio/src/slic3r/GUI/SkipPartCanvas.cpp: In lambda function:
/run/build/BambuStudio/src/slic3r/GUI/SkipPartCanvas.cpp:55:14: error: ‘map’ is not a member of ‘std’
   55 |         std::map<cv::Vec3b, int, std::function<bool(const cv::Vec3b &, const cv::Vec3b &)>> colorCount(
      |              ^~~
/run/build/BambuStudio/src/slic3r/GUI/SkipPartCanvas.cpp:13:1: note: ‘std::map’ is defined in header ‘<map>’; this is probably fixable by adding ‘#include <map>’
   12 | #include <filesystem>
  +++ |+#include <map>
   13 |